// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDDnTcl8GOlnc0jQe28QpXz-h_Mpbf9PE',
    appId: '1:522279942618:web:a30811904d3e958dda68e3',
    messagingSenderId: '522279942618',
    projectId: 'flashcard-app-e33db',
    authDomain: 'flashcard-app-e33db.firebaseapp.com',
    storageBucket: 'flashcard-app-e33db.appspot.com',
    measurementId: 'G-53SC9NQER5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDm3i_7GKdPPF7AeSYB2ya4Cf2fymMRgYE',
    appId: '1:522279942618:android:9d670319ddc8c1c6da68e3',
    messagingSenderId: '522279942618',
    projectId: 'flashcard-app-e33db',
    storageBucket: 'flashcard-app-e33db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApUURcuXqKLdLL93AyLSb-iKXJaOl4p1o',
    appId: '1:522279942618:ios:5ba24090ea0eeb5bda68e3',
    messagingSenderId: '522279942618',
    projectId: 'flashcard-app-e33db',
    storageBucket: 'flashcard-app-e33db.appspot.com',
    iosBundleId: 'com.example.flashcardAppMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApUURcuXqKLdLL93AyLSb-iKXJaOl4p1o',
    appId: '1:522279942618:ios:5ba24090ea0eeb5bda68e3',
    messagingSenderId: '522279942618',
    projectId: 'flashcard-app-e33db',
    storageBucket: 'flashcard-app-e33db.appspot.com',
    iosBundleId: 'com.example.flashcardAppMobile',
  );
}
